# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab2b9d6d1b27f44e75f1c36bccfe008904e0e6eb4e4d97619ed183d0b3bd8e30ff5d422c5efd543b29bbbdd54ce327d354338ae81c131bc5f08a8d3b135754b9

test:
  secret_key_base: 8a6824eb743000c2e617d2763382755b27ff674b13f16c2f4bc98a461f836806083e6a7cdb11d07803286eafe6cdff8fed88a4fddc08ddd132d5bc4368e7d868

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
